# Generated by Django 4.2.13 on 2024-08-08 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "attribute",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AttributeName",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                ("display", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "attribute_name",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "attribute_value",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.URLField()),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "image",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(max_length=3)),
                ("published_on", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "product",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.image"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
            ],
            options={
                "db_table": "product_image",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProductAttributes",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.attribute"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
            ],
            options={
                "db_table": "product_attributes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Catalog",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("attributes", models.ManyToManyField(to="api.attribute")),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.image",
                    ),
                ),
                ("products", models.ManyToManyField(to="api.product")),
            ],
            options={
                "db_table": "catalog",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="attribute",
            name="attribute_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.attributename"
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="attribute_value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.attributevalue"
            ),
        ),
    ]
